name: my_ryadom_backend
description: Minimal backend MVP for Мы Рядом.
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.11.1

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.4

dev_dependencies:
  lints: ^6.0.0
